[Sistema]
nombre = "Sistema Contabilidad"
version = "v1.1.0"
key_sesion = "Exland-Contabilidad"
produccion = false ; True - False


;========================================================
; Producción
;========================================================
[Produccion]
db.servidor = "localhost"
db.puerto = "3306"
db.usuario = "exlandcl_contadores"
db.clave = "GV(]{=A65W5F"
db.nombre = "exlandcl_santiagocontadores"
base_url = "https://gestion.santiagocontadores.cl" ;Debe incluir HTTP o HTPPS

;========================================================
; Desarrollo
;========================================================
[Desarrollo]
db.servidor = "localhost"
db.puerto = "3307"
db.usuario = "root"
db.clave = "root"
db.nombre = "exland_contadores"
base_url = "http://localhost/Exland-Contadores"